In [47]:
import torch
import networkx as nx
from torch_geometric.datasets import Planetoid
from torch_geometric.data import Data
from torch_geometric.transforms import RandomNodeSplit
import numpy as np
from torch_geometric.utils import from_networkx

In [2]:
dataset = Planetoid(
    root = 'data/planetoid',
    name = 'Cora')

In [4]:
type(dataset), len(dataset)

(torch_geometric.datasets.planetoid.Planetoid, 1)

In [5]:
graph = dataset[0]

In [7]:
graph.edge_index

tensor([[ 633, 1862, 2582,  ...,  598, 1473, 2706],
        [   0,    0,    0,  ..., 2707, 2707, 2707]])

In [8]:
graph.edge_index.shape

torch.Size([2, 10556])

In [9]:
graph.num_edges

10556

In [10]:
graph.num_nodes

2708

In [11]:
graph.x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [12]:
graph.x.shape

torch.Size([2708, 1433])

In [14]:
graph.x[0,:].sum()

tensor(9.)

In [15]:
target = graph.y

In [17]:
target.unique()

tensor([0, 1, 2, 3, 4, 5, 6])

In [20]:
graph.train_mask.dtype

torch.bool

In [24]:
graph.test_mask.sum().item()

1000

In [27]:
split = RandomNodeSplit(
    split = 'random',
    num_splits = 3,
    num_train_per_class = 20,
    num_val = 500,
    num_test = 1000
)
graph = split(graph)

In [28]:
graph.train_mask[:10]

tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

### NetworkX

In [37]:
g = nx.Graph()
g.add_node(0, x = [2,4])
g.add_node(1, x = [5,10])
g.add_edge(0,1, weight = 0.5 , year = [2025])

In [33]:
torch.Tensor(np.stack([data['x'] for _ , data in g.nodes(data = True)]))

tensor([[ 2.,  4.],
        [ 5., 10.]])

In [34]:
g.nodes[0]

{'x': [2, 4]}

In [38]:
g.adj[0]

AtlasView({1: {'weight': 0.5, 'year': [2025]}})

In [39]:
g.adj[1]

AtlasView({0: {'weight': 0.5, 'year': [2025]}})

In [40]:
g.adj[1][0]['year']

[2025]

In [44]:
mdg = nx.MultiDiGraph()
mdg.add_edge('A','B', relation_type = 'r1')
mdg.add_edge('A','B', relation_type = 'r2')
for edge in mdg.edges(data = True, keys = True):
    print(edge)

('A', 'B', 0, {'relation_type': 'r1'})
('A', 'B', 1, {'relation_type': 'r2'})


In [45]:
mdg = nx.MultiDiGraph()
mdg.add_edge('A','B', key = 'r1')
mdg.add_edge('A','B', key = 'r2')
for edge in mdg.edges(data = True, keys = True):
    print(edge)

('A', 'B', 'r1', {})
('A', 'B', 'r2', {})


In [48]:
from_networkx(g)

Data(x=[2, 2], edge_index=[2, 2], weight=[2], year=[2, 1])